{"uid":"a6b6f59aa8c78b8d","name":"test_error_without_traceback","fullName":"test.utilities.test_cli.TestAlertFunctions#test_error_without_traceback","historyId":"3046a012cff151115e61e02786daf834","time":{"start":1756775852625,"stop":1756775852625,"duration":0},"description":"Verify error() logs at the ERROR level without a traceback.","descriptionHtml":"<p>Verify error() logs at the ERROR level without a traceback.</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"test.utilities"},{"name":"suite","value":"test_cli"},{"name":"subSuite","value":"TestAlertFunctions"},{"name":"host","value":"dtc205659"},{"name":"thread","value":"530689-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.utilities.test_cli"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"59ec9c92f4f5e419","status":"passed","time":{"start":1756775768735,"stop":1756775768736,"duration":1}}],"categories":[],"tags":[]},"source":"a6b6f59aa8c78b8d.json","parameterValues":[]}
