{"uid":"3631b7e9506aa26e","name":"test_error_without_traceback","fullName":"test.utilities.test_cli.TestAlertFunctions#test_error_without_traceback","historyId":"3046a012cff151115e61e02786daf834","time":{"start":1756782280153,"stop":1756782280154,"duration":1},"description":"Verify error() logs at the ERROR level without a traceback.","descriptionHtml":"<p>Verify error() logs at the ERROR level without a traceback.</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"test.utilities"},{"name":"suite","value":"test_cli"},{"name":"subSuite","value":"TestAlertFunctions"},{"name":"host","value":"pkrvmccyg1gnepe"},{"name":"thread","value":"2173-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.utilities.test_cli"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":[]},"source":"3631b7e9506aa26e.json","parameterValues":[]}